Sprint1
ClevertecFrontendLab/sprint1-retrosexyal pull request #4
Opened 2023-01-28 11:44 UTC by retrosexyal

2023-01-28 11:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674906414/content-window.png)

2023-01-28 12:06 UTC, klichkovskiy commented on src/pages/book-page/book-page.tsx
> +          <p>ОАО &apos;Блаблабла&apos;</p>
![image](https://user-images.githubusercontent.com/62481116/215265540-6100943e-f769-4583-ad9f-636cd2e76f0f.png)
А чего это вдруг такой изготовитель? Сделай по макету!

2023-01-28 12:06 UTC, klichkovskiy commented on src/pages/book-page/book-page.tsx
> +          </div>
![image](https://user-images.githubusercontent.com/62481116/215265569-556c63ab-1bfa-4e2b-b550-261e01d8188b.png)
Сделай по макету

2023-01-28 12:11 UTC, klichkovskiy commented on src/components/book/book.tsx
> +        <div className={bookTheme ? styles.content : styles.content2}>
Названия классов должны быть говорящими. А не контент2

2023-01-28 12:12 UTC, klichkovskiy commented on src/components/book/index.js
> +export { Book } from './book';
А чего этот файл просто js ты ж вроде на TS пишешь.

2023-01-28 12:12 UTC, klichkovskiy commented on src/components/book/index.js
> +export { Book } from './book';
Далее по коду тоже самое

2023-01-29 05:51 UTC, retrosexyal commented on src/components/book/index.js
> +export { Book } from './book';
Исправил

2023-01-29 05:52 UTC, retrosexyal commented on src/components/book/book.tsx
> +              className={
Исправил

2023-01-29 05:52 UTC, retrosexyal commented on src/index.css
> +  src: local("Montserrat"), url(./assets/fonts/Montserrat-VariableFont_wght.ttf);
Исправил

2023-01-29 05:52 UTC, retrosexyal commented on src/pages/book-page/book-page.tsx
> +          </div>
Исправил

2023-01-29 08:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674982110/content-window.png)

2023-01-29 10:32 UTC, klichkovskiy requested changes
Исправь этих 2 мелких замечания!

2023-01-29 12:11 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/retrosexyal/1674994270/content-window.png)

2023-01-29 12:15 UTC, klichkovskiy approved these changes

2023-01-29 12:37 UTC, merged